/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.*;

/**
 *
 * @author Jose
 */
public class BadStuffView extends javax.swing.JPanel {

    /**
     * Creates new form BadStuffView
     */
    public BadStuffView() {
        initComponents();
    }
    
    private BadStuff badStuffModel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setBadStuffView(BadStuff bc){
        badStuffModel = bc;
        this.badStuff.setText(this.badStuffModel.getText());
        //Falta la imagen
        repaint();
    }
    public void reset(){
        this.badStuff.setText("...");
        repaint();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        badStuff = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 225, 188));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        jLabel2.setText("MAL ROLLO");
        jPanel3.add(jLabel2);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 225, 188));

        badStuff.setFont(new java.awt.Font("Trajan Pro", 1, 10)); // NOI18N
        badStuff.setText("...");
        jPanel2.add(badStuff);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel badStuff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
