/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.Monster;
import napakalaki.*;

/**
 *
 * @author Jose
 */
public class MonsterView extends javax.swing.JPanel {

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }
    private Monster monsterModel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setMonster(Monster m){
        monsterModel = m;
        this.name.setText(this.monsterModel.getName());
        this.combatLevel.setText("Nivel: "+Integer.toString(monsterModel.getBasicValue()));
        this.againstCultist.setText("VS. Sectario: "+Integer.toString(monsterModel.getSpecialValue()));
        this.image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstruos/"+monsterModel.getId()+".png")));
        this.badStuffView1.setBadStuffView(monsterModel.getBadStuff());
        this.prizeView1.setPrizeView(monsterModel.getPrize());
        //Falta la imagen
        repaint();
    }
    public void reset(){
        this.name.setText("Monstruo escondido...");
        this.combatLevel.setText("vas a morir");
        this.againstCultist.setText("muhahaha");
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartam.jpg"))); // NOI18N
        this.badStuffView1.reset();
        this.prizeView1.reset();
        //Falta la imagen
        repaint();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        badStuffView1 = new GUI.BadStuffView();
        prizeView1 = new GUI.PrizeView();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        againstCultist = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 225, 188));
        jPanel3.setName("características"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(181, 163));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartam.jpg"))); // NOI18N
        jPanel3.add(image);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(badStuffView1, java.awt.BorderLayout.NORTH);
        jPanel4.add(prizeView1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        add(jPanel3, java.awt.BorderLayout.CENTER);
        jPanel3.getAccessibleContext().setAccessibleName("");

        jPanel7.setBackground(new java.awt.Color(255, 225, 188));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 225, 188));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 225, 188));
        jPanel5.setLayout(new java.awt.BorderLayout());

        name.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/monster.png"))); // NOI18N
        name.setText("Monstruo Escondido....");
        jPanel5.add(name, java.awt.BorderLayout.NORTH);

        combatLevel.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        combatLevel.setText("VAS A MORIR");
        jPanel5.add(combatLevel, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(255, 225, 188));
        jPanel6.setLayout(new java.awt.BorderLayout());

        againstCultist.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        againstCultist.setText("MUAHAHAHA");
        jPanel6.add(againstCultist, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel7.add(jPanel1, java.awt.BorderLayout.WEST);

        add(jPanel7, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel againstCultist;
    private GUI.BadStuffView badStuffView1;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel name;
    private GUI.PrizeView prizeView1;
    // End of variables declaration//GEN-END:variables
}
