/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import napakalaki.*;

/**
 *
 * @author Jose
 */
public class NapakalakiView extends javax.swing.JFrame {
    Napakalaki napakalakiModel;
    JDialog frame = new JDialog();
    SystemSound sonidos;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        
        //treasureView1.setTreasureView(new Treasure("Clavo de rail ferroviario","t004", 200, 4, 7, TreasureKind.NECKLACE));
        //treasureView2.setTreasureView(new Treasure("Segunda prueba","t020", 200, 4, 7, TreasureKind.HELMET));
    }
    public void setNapakalaki(Napakalaki np){
        this.napakalakiModel = np;
        this.playerView1.setPlayerView(this.napakalakiModel.getCurrentPlayer());
        sonidos = SystemSound.getInstace();
        //this.monsterView1.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        monsterView1 = new GUI.MonsterView();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bCombat = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        playerView1 = new GUI.PlayerView();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 225, 188));
        setMinimumSize(new java.awt.Dimension(1266, 689));

        jPanel1.setBackground(new java.awt.Color(255, 225, 188));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 225, 188));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 348));
        jPanel3.setLayout(new java.awt.BorderLayout());

        monsterView1.setMinimumSize(new java.awt.Dimension(242, 240));
        jPanel3.add(monsterView1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 225, 188));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 225, 188));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        jLabel1.setText("COMBATIR:");
        jPanel7.add(jLabel1, java.awt.BorderLayout.NORTH);

        bCombat.setBackground(new java.awt.Color(102, 0, 0));
        bCombat.setForeground(new java.awt.Color(255, 255, 255));
        bCombat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fight.png"))); // NOI18N
        bCombat.setBorderPainted(false);
        bCombat.setFocusPainted(false);
        bCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombatActionPerformed(evt);
            }
        });
        jPanel7.add(bCombat, java.awt.BorderLayout.CENTER);

        nextTurn.setBackground(new java.awt.Color(255, 255, 255));
        nextTurn.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        nextTurn.setText("SIGUIENTE TURNO");
        nextTurn.setEnabled(false);
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });
        jPanel7.add(nextTurn, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel8.setBackground(new java.awt.Color(255, 225, 188));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel4.setText("Mal rollo pendiente:");
        jPanel8.add(jLabel4, java.awt.BorderLayout.NORTH);

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        jLabel5.setText("...");
        jPanel8.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(395, 346));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(playerView1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel6, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombatActionPerformed
        // TODO add your handling code here: 
                    
        this.monsterView1.setMonster(this.napakalakiModel.getCurrentMonster());
        CombatResult cr = this.napakalakiModel.developCombat();
        
        if(cr == CombatResult.Win){
            sonidos.stopSound("./src/Sounds/onehand.wav");
            sonidos.playSound("./src/Sounds/onehand.wav", false);
            JOptionPane.showMessageDialog(frame, "Derrotaste al monstruo"); 
        }

        if(cr == CombatResult.WinAndWinGame){
            sonidos.stopSound("./src/Sounds/victoria.wav");
            sonidos.playSound("./src/Sounds/victoria.wav", false);
            JOptionPane.showMessageDialog(frame, "Has ganado el juego!!");
            System.exit(0);
        }
        if(cr == CombatResult.Lose){
            this.jLabel5.setText(this.napakalakiModel.getCurrentMonster().getBadStuff().getText());
            sonidos.stopSound("./src/Sounds/punch.wav");
            sonidos.playSound("./src/Sounds/punch.wav", false);
            JOptionPane.showMessageDialog(frame, "Has perdido");
        }
        if(cr == CombatResult.LoseAndConvert){
            sonidos.stopSound("./src/Sounds/dead.wav");
            sonidos.playSound("./src/Sounds/dead.wav", false);
            JOptionPane.showMessageDialog(frame, "Has entrado en la secta... Ahora eres uno de los nuestros para siempre!!!!");
        }
        if(cr == CombatResult.LoseAndDie){
            sonidos.stopSound("./src/Sounds/bothhand.wav");
            sonidos.playSound("./src/Sounds/bothhand.wav", false);
            JOptionPane.showMessageDialog(frame, "Has muerto");
        }
        if(cr == CombatResult.LoseAndEscape){
            sonidos.stopSound("./src/Sounds/scape.wav");
            sonidos.playSound("./src/Sounds/scape.wav", false);
            JOptionPane.showMessageDialog(frame, "Escapaste por los pelos!!");
        }
        this.nextTurn.setEnabled(true);
        this.bCombat.setEnabled(false);
        this.setNapakalaki(this.napakalakiModel);
    }//GEN-LAST:event_bCombatActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        // TODO add your handling code here:
        if(this.napakalakiModel.nextTurn()){ 
            this.bCombat.setEnabled(true);
            this.nextTurn.setEnabled(false);
            
            this.monsterView1.reset();
            this.playerView1.setCompra(0);
            this.setNapakalaki(napakalakiModel);
            this.jLabel5.setText("...");
            
        }
        else{
            JOptionPane.showMessageDialog(frame, "Tienes un mal rollo pendiente o tienes mas de 5 cartas en mano!!");
        }
    }//GEN-LAST:event_nextTurnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView(){
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCombat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurn;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
