/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author juanantoniomarinsanchez
 */
import napakalaki.SystemSound;
public class PlayerNamesCapture extends javax.swing.JDialog {
    ArrayList<String> names = new ArrayList();
    JDialog frame = new JDialog();
    SystemSound sonidos;
    /**
     * Creates new form PlayerNamesCapture
     */
    public PlayerNamesCapture(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        sonidos = SystemSound.getInstace();
        sonidos.playSound("./src/Sounds/intro.wav", true);
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelPlayer1 = new javax.swing.JLabel();
        tfPlayer1 = new javax.swing.JTextField();
        labelPlayer2 = new javax.swing.JLabel();
        tfPlayer2 = new javax.swing.JTextField();
        labelPlayer3 = new javax.swing.JLabel();
        tfPlayer3 = new javax.swing.JTextField();
        bPlay = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imagePanel1 = new GUI.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 479));
        setMinimumSize(new java.awt.Dimension(620, 479));
        setPreferredSize(new java.awt.Dimension(620, 479));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 225, 188));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 225, 188));
        jPanel2.setForeground(new java.awt.Color(255, 225, 188));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 225, 188));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        labelPlayer1.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        labelPlayer1.setText("Player 1:");
        jPanel3.add(labelPlayer1);

        tfPlayer1.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jPanel3.add(tfPlayer1);

        labelPlayer2.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        labelPlayer2.setText("Player 2:");
        jPanel3.add(labelPlayer2);

        tfPlayer2.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jPanel3.add(tfPlayer2);

        labelPlayer3.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        labelPlayer3.setText("Player 3:");
        jPanel3.add(labelPlayer3);

        tfPlayer3.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jPanel3.add(tfPlayer3);

        bPlay.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        bPlay.setText("Jugar");
        bPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayActionPerformed(evt);
            }
        });
        jPanel3.add(bPlay);

        bCancel.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        bCancel.setText("SALIR");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel3.add(bCancel);

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setBackground(new java.awt.Color(255, 225, 188));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 11)); // NOI18N
        jLabel1.setText("   CREADO POR:");
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 11)); // NOI18N
        jLabel2.setText("   José Adrián Garrido Puertas");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 11)); // NOI18N
        jLabel3.setText("   Pablo Pérez Ruiz");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 11)); // NOI18N
        jLabel4.setText("   Juán Antonio Marín Sánchez");
        jPanel4.add(jLabel4);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        imagePanel1.setBackground(new java.awt.Color(255, 225, 188));
        jPanel1.add(imagePanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bCancelActionPerformed

    private void bPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayActionPerformed
        // TODO add your handling code here:
        if(tfPlayer1.getText().isEmpty()) 
            JOptionPane.showMessageDialog(frame, "Pon el nombre a jugador 1");
        else 
            if(tfPlayer2.getText().isEmpty()) 
                JOptionPane.showMessageDialog(frame, "Pon el nombre a jugador 2");
            else 
                if(tfPlayer3.getText().isEmpty())
                    JOptionPane.showMessageDialog(frame, "Pon el nombre a jugador 3");
                else if(
                        (tfPlayer1.getText().equals(tfPlayer2.getText()))
                        ||(tfPlayer1.getText().equals(tfPlayer3.getText()))
                        ||(tfPlayer2.getText().equals(tfPlayer3.getText()))
                        ){
                        JOptionPane.showMessageDialog(frame, "Nombres repetidos");
                         }
                            else{
                                names.add (tfPlayer1.getText());
                                names.add (tfPlayer2.getText());
                                names.add (tfPlayer3.getText());
                                // Similar para los otros dos nombres

                                sonidos.stopSound("./src/Sounds/intro.wav");
                                this.dispose();                            
                                }
    }//GEN-LAST:event_bPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public ArrayList<String> getNames(){
            this.setVisible(true);
            return names;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bPlay;
    private GUI.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelPlayer1;
    private javax.swing.JLabel labelPlayer2;
    private javax.swing.JLabel labelPlayer3;
    private javax.swing.JTextField tfPlayer1;
    private javax.swing.JTextField tfPlayer2;
    private javax.swing.JTextField tfPlayer3;
    // End of variables declaration//GEN-END:variables
}
