/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import napakalaki.*;

/**
 *
 * @author juanantoniomarinsanchez
 */
public class PlayerView extends javax.swing.JPanel {

    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    private Player playerModel;
    private Napakalaki napakalakiModel;
    SystemSound sonidos;
    JDialog frame = new JDialog();
    private int compra=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setPlayerView(Player p){
        playerModel = p;
        this.setNapakalaki(Napakalaki.getInstance());
        if(p instanceof CultistPlayer){ 
            this.cultistView1.setVisible(true);
            this.cultistView1.setCultist(((CultistPlayer)playerModel).getMyCultistCard());
        }
        else this.cultistView1.setVisible(false);
        //fillTreasurePanel (visibleTreasures, playerModel.getVisibleTreasures());
        //ArrayList<Treasure> tt = new ArrayList<Treasure>();
        //Tesoro de prueba
        //tt.add(new Treasure("Clavo de rail ferroviario","t004", 200, 4, 7, TreasureKind.NECKLACE));
        sonidos = SystemSound.getInstace();
        fillTreasurePanel (visibleTreasures, playerModel.getVisibleTreasures());
        fillTreasurePanel (hiddenTreasures, playerModel.getHiddenTreasures());
        this.name.setText(this.playerModel.getName());
        this.playerCombat.setText("Nivel de combate: "+Integer.toString(playerModel.getCombatLevel()));
        this.playerLevel.setText("Nivel de Jugador: "+Integer.toString(playerModel.getLevels()));
        repaint(); 
        revalidate();
    }
    public Player getPlayer(){
        return this.playerModel;
    }
    
    public void setNapakalaki(Napakalaki n){
        this.napakalakiModel = n;
    }
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
    // Se recorren los tesoros que contiene el panel,
    // almacenando en un vector aquellos que están seleccionados.
    // Finalmente se devuelve dicho vector.
    TreasureView tv;

    ArrayList<Treasure> output = new ArrayList();
    for ( Component c : aPanel.getComponents() ) {
        tv = (TreasureView) c;
        if ( tv.isSelected() )
            output.add ( tv.getTreasure() );
    }
    return output;
    }
    
    public void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua 
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        //    al panel 
        for (Treasure t : aList) { 
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasureView (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        } 
        // Se fuerza la actualización visual del panel 
        aPanel.repaint(); 
        aPanel.revalidate(); 
    } 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.JPanel();
        comprarLv = new javax.swing.JButton();
        equipar = new javax.swing.JButton();
        descartar = new javax.swing.JButton();
        regalar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tesoross = new javax.swing.JPanel();
        visibleTreasures = new javax.swing.JPanel();
        hiddenTreasures = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        nombres = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        playerLevel = new javax.swing.JLabel();
        playerCombat = new javax.swing.JLabel();
        cultista = new javax.swing.JPanel();
        cultistView1 = new GUI.CultistView();

        setLayout(new java.awt.BorderLayout());

        botones.setBackground(new java.awt.Color(255, 225, 188));
        botones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comprarLv.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        comprarLv.setText("Comprar Niveles");
        comprarLv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarLvActionPerformed(evt);
            }
        });
        botones.add(comprarLv);

        equipar.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        equipar.setText("Equipar");
        equipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiparActionPerformed(evt);
            }
        });
        botones.add(equipar);

        descartar.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        descartar.setText("Descartar Tesoro");
        descartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarActionPerformed(evt);
            }
        });
        botones.add(descartar);

        regalar.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        regalar.setText("REGALAR TESORO");
        regalar.setActionCommand("Regalar Tesoro");
        regalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regalarActionPerformed(evt);
            }
        });
        botones.add(regalar);

        add(botones, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tesoross.setBackground(new java.awt.Color(255, 255, 255));
        tesoross.setLayout(new java.awt.GridLayout(2, 1));

        visibleTreasures.setBackground(new java.awt.Color(19, 82, 17));
        visibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tesoros Visibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trajan Pro", 0, 10), java.awt.Color.white)); // NOI18N
        visibleTreasures.setForeground(new java.awt.Color(255, 255, 255));
        tesoross.add(visibleTreasures);

        hiddenTreasures.setBackground(new java.awt.Color(19, 82, 17));
        hiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tesoros Ocultos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trajan Pro", 0, 10), java.awt.Color.white)); // NOI18N
        tesoross.add(hiddenTreasures);

        jPanel1.add(tesoross, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(255, 225, 188));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setMinimumSize(new java.awt.Dimension(292, 390));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 290));
        jPanel9.setLayout(new java.awt.BorderLayout());

        nombres.setBackground(new java.awt.Color(255, 225, 188));
        nombres.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 225, 188));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        name.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        name.setText("Nombre Jugador");
        jPanel5.add(name);
        name.getAccessibleContext().setAccessibleDescription("");

        playerLevel.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        playerLevel.setText("level");
        jPanel5.add(playerLevel);

        playerCombat.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        playerCombat.setText("Nivel de combate:");
        jPanel5.add(playerCombat);

        nombres.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel9.add(nombres, java.awt.BorderLayout.NORTH);

        cultista.setBackground(new java.awt.Color(255, 225, 188));
        cultista.setLayout(new java.awt.BorderLayout());

        cultistView1.setBorder(null);
        cultista.add(cultistView1, java.awt.BorderLayout.NORTH);

        jPanel9.add(cultista, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel9, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void equiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiparActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures (this.hiddenTreasures);
        napakalakiModel.makeTreasureVisible (selHidden);
        setPlayerView (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_equiparActionPerformed

    private void descartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures (this.hiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures (this.visibleTreasures);
        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);
        setPlayerView (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_descartarActionPerformed

    private void comprarLvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarLvActionPerformed
        // TODO add your handling code here:
        sonidos.stopSound("./src/Sounds/gold.wav");
        sonidos.playSound("./src/Sounds/gold.wav", false);
        ArrayList<Treasure> selHidden = getSelectedTreasures (this.hiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures (this.visibleTreasures);
        napakalakiModel.buyLevels(selVisible, selHidden);
        setPlayerView (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_comprarLvActionPerformed

    private void regalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regalarActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> tesoro = getSelectedTreasures (this.hiddenTreasures);
        if(compra==0){
            if(tesoro.size()>1)
                JOptionPane.showMessageDialog(frame, "Demasiados tesoros");
            else{
                boolean sePuede = napakalakiModel.regalarTesoro(tesoro);
                if(sePuede){
                    JOptionPane.showMessageDialog(frame, "Tesoro regalado. Un jugador te da las gracias");
                }else{
                    JOptionPane.showMessageDialog(frame, "No se pudo realizar el regalo");
                }
            }
            setPlayerView (napakalakiModel.getCurrentPlayer());
            setCompra(1);
        }else
            JOptionPane.showMessageDialog(frame, "Ya has regalado una vez en este runo");      
    }//GEN-LAST:event_regalarActionPerformed
    public int getCompra(){return compra;}
    public void setCompra(int i){compra=i;}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton comprarLv;
    private GUI.CultistView cultistView1;
    private javax.swing.JPanel cultista;
    private javax.swing.JButton descartar;
    private javax.swing.JButton equipar;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel name;
    private javax.swing.JPanel nombres;
    private javax.swing.JLabel playerCombat;
    private javax.swing.JLabel playerLevel;
    private javax.swing.JButton regalar;
    private javax.swing.JPanel tesoross;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
