/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.Prize;

/**
 *
 * @author Jose
 */
public class PrizeView extends javax.swing.JPanel {

    /**
     * Creates new form PlayerView2
     */
    public PrizeView() {
        initComponents();
    }
    private Prize prizeModel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setPrizeView(Prize p){
        prizeModel = p;
        this.treasures.setText(Integer.toString(prizeModel.getTreasures()));
        this.levels.setText(Integer.toString(prizeModel.getLevel()));
        repaint();
    }
    public void reset(){
        this.treasures.setText("...");
        this.levels.setText("...");
        repaint();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        levels = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        treasures = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        levels.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        levels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lvl.png"))); // NOI18N
        levels.setText("...");
        jPanel2.add(levels);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        treasures.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        treasures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/treasure.png"))); // NOI18N
        treasures.setText("...");
        jPanel4.add(treasures);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        jLabel2.setText("PREMIOS");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel2);

        add(jPanel3, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel treasures;
    // End of variables declaration//GEN-END:variables
}
