/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Treasure;
import napakalaki.TreasureKind;

/**
 *
 * @author juanantoniomarinsanchez
 */
public class TreasureView extends javax.swing.JPanel {
    Treasure treasureModel;
    private boolean selected=false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    public void setTreasureView(Treasure t){
        treasureModel = t;
        //Cambia las monedas de oro
        this.labelPiezasOro.setText(Integer.toString(treasureModel.getGoldCoins()));
        //Cambia los bonus
        this.labelBonus.setText("+"+Integer.toString(treasureModel.getMinBonus())+"/+"+Integer.toString(treasureModel.getMaxBonus()));
        this.labelNombre.setText(" "+treasureModel.getName()+" ");
        //Cambia la imagen del tesoro
        this.bImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tesoros/"+treasureModel.getId()+".png")));
        //this.labelTipo.setText(treasureModel.getType().toString());
        //Icono del tipo
        if(treasureModel.getType() == TreasureKind.ARMOR){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/armor.png")));
            bTipo.setToolTipText("Armor");
        }
        if(treasureModel.getType() == TreasureKind.BOTHHAND){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bothhand.png")));
            bTipo.setToolTipText("Both Hand");
        }
        if(treasureModel.getType() == TreasureKind.HELMET){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/helmet.png")));
            bTipo.setToolTipText("Helmet");
        }
        if(treasureModel.getType() == TreasureKind.NECKLACE){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/necklace.png")));
            bTipo.setToolTipText("Necklace");
        }
        if(treasureModel.getType() == TreasureKind.ONEHAND){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/onehand.png")));
            bTipo.setToolTipText("One Hand");
        }
        if(treasureModel.getType() == TreasureKind.SHOE){
            this.bTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoe.png")));
            bTipo.setToolTipText("Shoe");
        }
        repaint();
    }
    
    public boolean isSelected(){
        return this.selected;
    }
    
    public Treasure getTreasure(){
        return this.treasureModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTesoro = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bTipo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelMoneda = new javax.swing.JLabel();
        labelPiezasOro = new javax.swing.JLabel();
        labelEspada = new javax.swing.JLabel();
        labelBonus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(new javax.swing.border.MatteBorder(null));
        setMaximumSize(new java.awt.Dimension(100, 300));
        setMinimumSize(new java.awt.Dimension(100, 300));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        labelTesoro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/treasure.png"))); // NOI18N
        jPanel1.add(labelTesoro);

        labelNombre.setFont(new java.awt.Font("Trajan Pro", 1, 10)); // NOI18N
        labelNombre.setText("Nombre");
        labelNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelNombre);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        bImagen.setBackground(new java.awt.Color(255, 255, 255));
        bImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tesoros/t001.png"))); // NOI18N
        jPanel2.add(bImagen);
        jPanel2.add(jLabel1);
        jPanel2.add(jLabel2);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(new java.awt.BorderLayout());

        bTipo.setToolTipText("Tipo");
        jPanel3.add(bTipo, java.awt.BorderLayout.EAST);

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        labelMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gold.png"))); // NOI18N
        jPanel4.add(labelMoneda);

        labelPiezasOro.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        labelPiezasOro.setText("x piezas de oro               ");
        jPanel4.add(labelPiezasOro);

        labelEspada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sword.png"))); // NOI18N
        jPanel4.add(labelEspada);

        labelBonus.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        labelBonus.setText("Bonus      ");
        jPanel4.add(labelBonus);

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(this.selected==false){ 
            this.selected = true;
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
            
        }
        else {
            this.selected = false;
            setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bImagen;
    private javax.swing.JLabel bTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelBonus;
    private javax.swing.JLabel labelEspada;
    private javax.swing.JLabel labelMoneda;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPiezasOro;
    private javax.swing.JLabel labelTesoro;
    // End of variables declaration//GEN-END:variables
}
